project:
  type: website

website:
  title: "PIFSC Stock Assessments"

  sidebar:
    title: "PIFSC Stock Assessments"
    style: "docked"
    background: "light"
    align: left
    tools:
      - icon: github
        text: "Source Code"
        href: https://github.com/PIFSCstockassessments/quarto-website-proto
    contents:
      - text: "Index"
        href: index.qmd
      - text: "About Us"
        href: about.qmd
      - text: "---"
      - text: "Life History"
        href: life-history/section-LifeHistory.qmd
      - text: "---"
      - section: "Surveys"
        href: fish-surveys/section-surveys.qmd
        contents:
          - fish-surveys/mhi-mrip.qmd
          - fish-surveys/mhi-bottomfish.qmd
      - text: "---"
      - section: "Stock Assessments"
        href: assessments/section-assessments.qmd
        contents:
          - assessments/blue-marlin.qmd
          - assessments/blue-shark.qmd
          - assessments/kona-crab.qmd
          - assessments/mako-shark.qmd
          - assessments/mhi-deep7-bottomfish.qmd
          - assessments/reeffish.qmd
          - assessments/striped-marlin.qmd
          - assessments/swordfish.qmd
          - assessments/uku-snapper.qmd
          - assessments/us-jurisdictional-bottomfish.qmd
      - text: "---"
      - section: "Tools & Packages"
        href: tools-pkgs/section-toolsPackages.qmd
        contents:
          - tools-pkgs/ss3diags.qmd
          - tools-pkgs/JABBA.qmd
          - tools-pkgs/agepro.qmd
          - tools-pkgs/stepwiseLH.qmd
          - tools-pkgs/ss3grid.qmd


format:
  html:
    theme:
      light: [flatly, theme.scss]
      dark: [darkly, theme-dark.scss]
    toc: true

editor:
  mode: source

