project:
  type: website

website:
  title: "PIFSC Stock Assessments"
  sidebar:
    style: "floating"
    contents:
      - text: "Index"
        href: index.qmd
      - section: "Stock Recruitment"
        href: assessments.qmd
        contents:
          - assessments/blue-marlin.qmd
          - assessments/blue-shark.qmd
          - assessments/kona-crab.qmd
          - assessments/mako-shark.qmd
          - assessments/mhi-deep7-bottomfish.qmd
          - assessments/reeffish.qmd
          - assessments/striped-marlin.qmd
          - assessments/swordfish.qmd
          - assessments/uku-snapper.qmd
          - assessments/us-jurisdictional-bottomfish.qmd
      - section: "Surveys"
        href: fish-surveys/surveys.qmd
        contents:
        - fish-surveys/mhi-mrip.qmd
      - section: "Tools & Packages"
        href: tools-pkg/tools-packages.qmd
        contents:
          - tools-pkg/ss3diags.qmd
          - tools-pkg/JABBA.qmd
          - tools-pkg/agepro.qmd
          - tools-pkg/stepwiseLH.qmd
          - tools-pkg/ss3grid.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  mode: source

