project:
  type: website

website:
  title: "PIFSC Stock Assessments"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "floating"
    contents:
      - text: "Index"
        href: index.qmd
      - section: "Stock Recruitment"
        href: assessments.qmd
        contents:
          - assessments/blue-marlin.qmd
          - assessments/blue-shark.qmd
          - assessments/kona-crab.qmd
          - assessments/mako-shark.qmd
          - assessments/mhi-deep7-bottomfish.qmd
          - assessments/reeffish.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  mode: source

