---
title: "About Us"
---

The Stock Assessment Program is a part of Pacific Islands Fisheries Science Center’s (PIFSC) Fisheries Research and Monitoring Division (FRMD).

The Stock Assessment Program conducts research on population biology, stock assessment, and population modeling. The Program integrates biological, ecological, and oceanographic data to advance stock assessments and to inform conservation and resource management at both the species and ecosystem levels.

The Stock Assessment Program also provides statistical expertise to the NOAA Fisheries Pacific Islands Regional Office (PIRO) longline fishery observer program and uses data collected by the observers to estimate the magnitude of incidental takes of sea turtles, seabirds, and marine mammals, and the bycatch of non-marketed fish species (mostly sharks) in the Hawaii longline fishery.

The stock assessments, along with bycatch estimates, are provided to support informed decisions by PIRO, the Western Pacific Regional Fishery Management Council (WPFMC), and international organizations such as the Western and Central Pacific Fisheries Commission (WCPFC), the International Scientific Committee for Tuna and Tuna-like Species in the North Pacific Ocean (ISC), and the Inter-American Tropical Tuna Commission (IATTC).

# Disclaimer

The United States Department of Commerce (DOC) GitHub project code is provided on an ‘as is’ basis and the user assumes responsibility for its use. DOC has relinquished control of the information and no longer has responsibility to protect the integrity, confidentiality, or availability of the information.

Any claims against the Department of Commerce stemming from the use of its GitHub project will be governed by all applicable Federal law.

Any reference to specific commercial products, processes, or services by service mark, trademark, manufacturer, or otherwise, does not constitute or imply their endorsement, recommendation or favoring by the Department of Commerce.

The Department of Commerce seal and logo, or the seal and logo of a DOC bureau, shall not be used in any manner to imply endorsement of any commercial product or activity by DOC or the United States Government. About this site
