---
title: Assessments 
---

[Stock assessment](https://www.fisheries.noaa.gov/topic/population-assessments#fish-stocks) is at the core of NOAA's science-based management objectives and is the primary function of the PIFSC Stock Assessment Program (SAP).

The Assessment Program (SAP) at the NOAA Pacific Islands Fisheries Science center conducts evaluations of the current and historical population status of bottomfish species and crustaceans in support of the Western Pacific Regional Fishery Management Council (WPRFMC) management plans for the nation’s fisheries based in the Western Pacific Region. The WPRFMC and NOAA Fisheries use these evaluations to set Annual Catch Limits (ACLs).

The SAP also performs analyses in support of U.S. participation in international Regional Fishery Management Organizations (RFMOs).

For example, the SAP works with scientists from other nations within the International Scientific Committee on Tuna and Tuna-like Species in the North Pacific Ocean (ISC) to conduct collaborative stock assessments on tuna, billfish and shark stocks spanning the Pacific, supporting fisheries worth many billions of dollars and making critical contribution to the Pacific Islands regional economy.

SAP scientists play an essential role in these international stock assessments, including serving as lead analysts and chairing working groups.

In addition to conducting stock assessments, other crucial activities developed by the SAP include:

-   Helping the design and implementation of the annual Bottomfish Fishery-Independent Survey in Hawaii (BFISH). The BFISH assesses the number and size of bottomfish around all eight of the Main Hawaiian Islands by collecting data at various scientifically-selected sites.

-   Apply advanced statistical methods to analyze catch and effort data from the recreational and subsistence fishing conducted in Hawaii and the U.S. territories of Western Pacific Region, which includes American Samoa, Guam, and the Commonwealth of the Northern Mariana Islands.

-   Host the NMFS Cooperative Research Program. Cooperative research provides a means for commercial and recreational fishermen to become involved in the collection of important fisheries information to support the development and evaluation of fishery management options.
