---
title:  Hawaii Marine Recreational Information Program (MRIP)
---

Non-commercial fisheries in the Pacific Islands region are major economic contributors to coastal communities and have important social and cultural significance [(https://www.fisheries.noaa.gov/feature-story/saltwater-recreational-fisheries-regional-snapshots)](https://www.fisheries.noaa.gov/feature-story/saltwater-recreational-fisheries-regional-snapshots).

The Marine Recreational Information Program (MRIP) has been actively involved with the Hawaii Marine Recreational Fishing Survey (HMRFS). A survey statistician from the Fisheries Research and Monitoring Division (FRMD) or Integrated Fisheries Management Plan (IFMP) assists in coordinating and monitoring the execution of the HMRFS <http://doi.org/10.7289/V5/TM-PIFSC-55>.

MRIP has worked with other partners to carry out several MRIP projects, review HMRFS and test alternative survey methods. The major MRIP projects in Hawaii include:

-   The Hawaii For-Hire Pilot Study to Incorporate Validation Procedures in the Commercial Marine License Reporting Program documented the “for-hire” (charter boat) sector’s level of compliance with the Hawaii Division of Aquatic Resources (DAR) commercial fish catch reporting system : <https://repository.library.noaa.gov/view/noaa/4605>

    -   Identified a series of recommended changes to improve the system: <http://doi.org/10.7289/V5XG9P4S>

-   Review of the Current Sampling and Estimation Methods of the Hawaii Marine Recreational Fishing Survey (HMRFS), completed by a team of expert consultants, identifies opportunities and makes recommendations to improve the angler catch survey and the Coastal Household Telephone Survey in Hawaii (project report at <http://doi.org/10.7289/V5/TM-PIFSC-55>)

-   Design Effort Surveys for Shoreline Fishing in Hawaii Marine Recreational Fishing Survey (HMRFS) came up with alternative survey approaches for collecting shore-based fishing-effort information, following the recommendations from the 2012 Workshop (Report available at [https://www.researchgate.net/publication/313821171)](https://www.researchgate.net/publication/313821171).

-   A MRIP workshop ws held in Honolulu on May 28-30, 2019, to review the pros and cons of the pilot surveys previously tested in Hawaii and develop certified surveys for the Hawaii Marine Recreational Fishing Survey (project report at [https://doi.org/10.25923/2pta-zs36)](https://doi.org/10.25923/2pta-zs36)
