---
title: Hawaii Bottomfish Surveys
---

The Bottomfish Fishery-Independent Survey in Hawai‘i (BFISH) is a collaborative survey conducted annually since 2016, by researchers at the Pacific Islands Fisheries Science Center and local cooperative research fishers.

The goal of the survey is to provide fishery-independent estimates of bottomfish abundance for use in the Deep 7 bottomfish stock assessment.

## Survey Details

This survey comprises two gear types:

1.  Hook and line fishing conducted by cooperative research fishers.
2.  Underwater stereo-cameras called MOUSS (Modular Optical Underwater Survey System).

Sampling locations are chosen at random each year based on habitat type. During the survey period, which typically runs from August through October, fishing for bottomfish occurs for 30 minutes at each location using two lines, each baited with four standard-size hooks. PIFSC researchers also deploy cameras from a NOAA research vessel. For both gear types, all fish caught or seen are recorded, counted, and measured.

[Learn more about the Hawaii Bottomfish Survey (NOAA Fisheries)](https://www.fisheries.noaa.gov/feature-story/imaged-depths-survey-bottomfish-main-hawaiian-islands)
