---
title: Blue Shark
---

Blue shark (*Prionace glauca*) are widely distributed throughout temperate and tropical surface waters of the Pacific Ocean. They are classified as highly migratory species (HMS) and divided into two stocks in the Pacific, North and South. Historically, blue sharks were caught as bycatch in fisheries targeting other species, primarily high seas tuna and swordfish fisheries.

The North Pacific blue shark stock is assessed by the International Scientific Committee for Tuna and Tuna-like Species (ISC) [Shark Working Group]({{< var partner.SHARKWG.href >}}) (SHARKWG) which was created by the ISC in 2011. The SHARKWG is a collaborative effort between scientists from ISC Member nations and observers to regularly evaluate the status of pelagic sharks that interact with international tuna and billfish fisheries in the North Pacific Ocean and provide scientific advice for conservation efforts.

*Stock status and conservation information is based on the most current assessment (e.g., **2022**) unless specified otherwise. Descriptions of previous stock assessments are included for historical perspective.*

-   The **2017** stock assessment of blue shark in the North Pacific Ocean used a fully integrated size-structured model within Stock Synthesis. The assessment model included time-series data from 1978 to 2015 (catch, relative abundance, and sex-specific length composition from multiple fisheries), biological information, and a newly developed low-fecundity stock-recruitment relationship (LFSR). The LFSR helped characterize productivity of the stock based on plausible life history information available for the North Pacific blue shark stock.

-   The **2022** stock assessment of blue shark in the North Pacific Ocean built off the previous 2017 fully integrated size-structured model within Stock Synthesis. Model inputs (catch, relative abundance, and sex-specific length composition data) were updated through 2020 and the full model period spanned 1971 to 2020. A notable change from the 2017 stock assessment was the move to an ensemble modeling framework to formulate the stock status and conservation information. Three models were considered in the ensemble. These models considered alternative relative abundance index assumptions for the recent model period (1994-2020), and alternative treatments of the effective sample size for small-scale Taiwanese longline fisheries length composition data.

## Publications

-   [ISC SHARKWG 2017 Assessment Report (PDF)](http://isc.fra.go.jp/pdf/ISC17/ISC17_Annex13-Stock_Assessment_and_Future_Projections_of_Blue_Shark.pdf)
-   [ISC SHARKWG 2022 Assessment Report (PDF)](https://isc.fra.go.jp/pdf/ISC22/ISC22_ANNEX12_Stock_Assessment_for_Blue_Shark.pdf)
