---
title: Blue marlin
---

Pacific blue marlin (*Makaira nigricans*) are found in tropical and subtropical waters of the Pacific Ocean and assessed as a single stock within the Pacific Ocean. Blue marlin are predominantly caught by Japanese, Korean, and Taiwanese high seas longline fisheries. In the 1950s and 1960s, bycatch of blue marlin in Japanese longline fisheries represented the largest portion of blue marlin take. In more recent years, Japanese efforts have decreased while efforts by Taiwanese and other Indo-Pacific countries (Korea, China, Indonesia, and French Polynesia) have increased.

Because of the species' wide range and long-distance migrations, the stock is assessed by the International Scientific Committee for Tuna and Tuna-like Species in the North Pacific (ISC) [Billfish Working Group (BILLWG)]({{< var partner.BILLWG.href >}}), which is a collaborative effort between multinational and multi-regional fisheries management organizations that conducts assessments and provides scientific advice for swordfish and marlin species.

The most recent benchmark assessment was developed in 2021. The 2021 assessment consisted of two age-, length-, and sex-structured Stock Synthesis models that incorporated sex-specific growth and natural mortality rates to account for sexual dimorphism of adults, each using a different growth curve for Pacific blue marlin.

After extensive model exploration, neither growth curve could be excluded due to model diagnostics, model fit, nor biological plausibility. Therefore, the best fit model using each growth curve was averaged to produce stock status and conservation information.

The assessment models included time-series data from 1971 to 2019 catch, relative abundance, and length and weight composition from multiple fisheries), and biological information.

## Publications

-   [ISC BILLWG 2021 Assessment Report (PDF)](http://isc.fra.go.jp/pdf/ISC21/ISC21_ANNEX10_Stock_Assessment_for_Pacific_Blue_Marlin.pdf)
