---
title: Kona Crab
---

Kona crabs (*Ranina ranina*, also known as "spanner crabs") are found throughout the tropical and subtropical Indo-Pacific region including around the Main Hawaiian Islands in waters of 2-200 m depth. Kona crabs have been commercially fished in Hawai'i since the beginning of the 20th century and are caught using baited hoop nets deployed over sandy substrates.The current annual catch limit (ACL) for Kona crab in the main Hawaiian Islands is 30,802 lb based on results from the latest stock assessment (Kapur et al. 2019). The 2018 Kona crab assessment used a state-space Bayesian framework that fit standardized CPUE data in a generalized Pella-Tomlinson surplus production model using Just Another Bayesian Biomass Assessment [Just Another Bayesian Biomass Assessment (JABBA)](/packages/JABBA/).

In the years since the assessment, the annual commercial catch was always less than 6,000 lb, well below the ACL. The commercial catch reported from inshore reporting areas (extending to \~2 nautical miles from shore) accounted for more than 80% of the total commercial catch in 2014-2024. Before then, catch from Penguin Bank (\> 3 nautical miles from shore, in federal waters) accounted for 50% of the total catch. However, there was minimal catch reported from Penguin Bank since 2014 and catch from federal waters as a whole was minor. The inshore reporting areas for the commercial Fisher Reporting System (FRS) only extend to about 2 nautical miles from shore and do not include all state waters, which extend to 3 nautical miles from shore. The actual annual catch in state waters may have accounted for \~90% or more of the total catch in 2014-2024. Considering the recent low annual commercial catch (average of 3,400 lb or 10% of ACL) and the small proportion of total catch in federal waters, an update stock assessment for Kona crab may not be warranted at this time.

## Repository

<https://github.com/hgmagithub/Kona-crab-fishery-in-the-Main-Hawaiian-Islands>

## Publications

-   Kapur, Maia; Fitchett, M. D; Yau, Annie; Carvalho, Felipe. 2019. [2018 Benchmark Stock Assessment of Main Hawaiian Islands Kona Crab](https://repository.library.noaa.gov/view/noaa/19592)

