---
title: Mako Shark
---

Shortfin mako sharks (*Isurus oxyrinchus*) are found throughout the pelagic, tropical to temperate, North Pacific Ocean and based on genetic and tagging evidence, it is assumed to be a single stock across the North Pacific Ocean.

Shortfin mako sharks are a highly migratory species and one of the focal species of the International Scientific Committee for Tuna and Tuna-like Species (ISC) [Shark Working Group]({{< var partner.SHARKWG.href >}}) (SHARKWG). The North Pacific stock is assessed by the SHARKWG which is a collaborative effort between scientists from ISC Member nations and observers to regularly evaluate the status of pelagic sharks that interact with international tuna and billfish fisheries in the North Pacific Ocean and provide scientific advice for conservation efforts.

*Stock status and conservation information is based on the most current assessment (e.g., 2024) unless specified otherwise. Descriptions of previous stock assessments are included for historical perspective.*

-   The 2018 stock assessment was the first full stock assessment of shortfin mako shark in the North Pacific Ocean. Prior to this assessment, an index-based approach was used to evaluate the status of the stock. Significant improvements to fishery and biological data availability allowed for the development of a length-based, age-structured assessment model in [Stock Synthesis](https://github.com/nmfs-ost/ss3-source-code) in 2018. That model incorporated time-series data of catch, catch-per-unit-effort, and sex-specific length-composition for fishing years 1975 to 2016.

-   The 2024 stock assessment represented a strategic shift in modeling approach and applied a Bayesian Surplus Production Model (BSPM) as revision of historical catch data and removal of the early relative abundance index made it challenging to reconcile the recent catch and index data with the biological assumptions in the Stock Synthesis model. Stock status is provided from 1994-2022. Public GitHub repositories for the stock assessment model files in the Transparent Assessment Format (TAF) and a Shiny app are available (TAF & Shiny).

    -   [2024 Mako Shark TAF](https://github.com/N-DucharmeBarth-NOAA/2024-npo-sma-taf)
    -   [2024 Mako Shark Shiny App](https://github.com/N-DucharmeBarth-NOAA/2024-npo-sma-shiny)

## Publications

-   [ISC SHARKWG 2018 Assessment Report (PDF)](http://isc.fra.go.jp/pdf/ISC18/ISC_18_ANNEX_15_Shortfin_Mako_Shark_Stock_Assessment_FINAL.pdf)
