---
title: Main Hawaiian Islands Deep 7 Bottomfish
---

The Hawaiian "Deep 7" bottomfish complex is comprised of six snapper and one grouper species: **‘ōpakapaka** (pink snapper), **onaga** (longtail snapper), **ehu** (squirrelfish snapper), **kalekale** (Von Siebold's snapper), **gindai** (Brigham's snapper), **lehi** (silverjaw snapper), and **hapu'upu'u** (Hawaiian grouper). These seven species are found around the Main Hawaiian Islands (MHI) in waters of 100-400 m depth.

The Deep 7 species have historical cultural significance in Hawaiian tradition and today they comprise a significant part of the domestic commercial catch, with reported catches ranging from about 200,000 lbs to 300,000 lbs per year. Although the efficiency of the modern fishery has likely improved through time, the current Hawaii bottomfish fishery still uses traditional deep handline capture methods for commercial and recreational harvest. The stock is jointly managed by the from the [State of Hawaii Division of Aquatic Resources (DAR)](https://dlnr.hawaii.gov/dar/) and NOAA.

The latest benchmark assessment was developed in 2024. The assessment used a Bayesian surplus production model that fit annual biomass estimates to bottomfish catch and effort data (CPUE) and commercial catch reports for fishing years 1949-2023 in addition to fishery-independent survey data starting in fishing year 2017.

Some significant changes implemented with the 2024 benchmark assessment include the re-examination of previously used reporting ratios for determining non-commercial catch, refining data filtering procedures and improving the generation of abundance indices (i.e., the standardized fishery-dependent CPUE index, fishery-independent index, and single-species **‘ōpakapaka** CPUE index), updating the software for the assessment model, exploring new parameterizations of the production function, and reevaluating prior distributions based on the most recent life-history information available for Deep 7 species.

The benchmark assessment indicated the main Hawaiian Islands Deep 7 complex was not overfished or undergoing overfishing in 2023.

-   Syslo J, Oshima M, Ma H, Ducharme-Barth N, Nadon M,Carvalho F. 2024. [Benchmark Stock Assessment for the Main Hawaiian Islands Deep 7 Bottomfish Complex in 2024, with Catch Projections Through 2029](https://www.fisheries.noaa.gov/resource/document/benchmark-stock-assessment-main-hawaiian-islands-deep-7-bottomfish-complex-2024).

## Research

A research track stock assessment was initiated for the main Hawaiian Islands bottomfish complex in 2024. Research objectives include improving the estimation of noncommercial catch, optimizing the Bottomfish Fishery-independent Survey in Hawaii (BFISH), and assessing the need and feasibility for transitioning to single-species or subcomplexes for assessment and management. The fishing community and State of Hawaii are important partners in this research.

Recently, an approach was developed to estimate the recreational component of the Deep 7 fishery that relies on using the Bottomfish Vessel Registry.[The Deep 7 Catch Analysis Tool](https://connect.fisheries.noaa.gov/content/093fc1b8-928f-4ee0-8c3d-bae82dc78295), an iteractive shiny web application, was developed to aid in assessing the effects of decision points on the estimated recreational catch using the new approach.

Simulation studies are currently underway to determine the optimal allocation of effort in the BFISH survey to inform stock assessment and the optimal degree of species resolution for assessing the complex.
