---
title: Reef Fish
---

The coral reef fish assessments are centered on the hundreds of targeted species that inhabit the nearshore environment around the Pacific Islands. The high species diversity, the mixture of commercial and recreational fishing effort, and the spatially diffused nature of these fisheries result in a comparatively data-poor situation for these stocks.

Due to the lack of available fishery-dependent and fishery-independent data, previous management regulations set by the [Western Pacific Regional Fishery Management Council (WPRFMC)](https://www.wpcouncil.org/) were based on empirical methods. However, since the early 2000s, fishery-independent survey efforts and life-history research by the Pacific Islands Fisheries Science Center (PIFSC) improved data availability which allowed statistical assessment models to be applied in order to better understand the status of reef fish stocks in the region.

## 2017 Hawaii

The coral reef fishery around the main Hawaiian islands is predominantly near-shore recreational and subsistence fishing, with a small commercial fishing sector. The most common fishing gear types include spears, hook-and-line, traps, and small gill and cast nets. The primary families caught include jacks and snappers, as well as some surgeonfish, goatfish, soldierfish, and parrotfish.

In 2016, a stock assessment for the 27 most commonly exploited reef-associated fishes surrounding the main Hawaiian Islands was conducted. The assessment used a novel approach for data-poor stocks to estimate life history parameters for 11 of the 27 species and a simple age-based assessment model. Fishery-independent size composition and diver survey abundance data, along with fishery-dependent catch data were incorporated into the model. The input data were available from 2003 to 2016.

-   Nadon, Marc O. 2017. [Stock assessment of the coral reef fishes of Hawaii, 2016](https://repository.library.noaa.gov/view/noaa/13291)

## 2019 Guam

The coral reef fishery around Guam is a mix of commercial and noncommercial fishing and it plays a key role in their culture and society. The dominant fishing gears are boat-based trolling and shore-based hook and line and the primary families caught include surgeonfishes, rabbitfishes, goatfishes, parrotfishes, snappers, and groupers.

The most recent stock assessment for the Guam reef fish stock was conducted in 2019 and included 12 of the most commonly exploited reef fish stocks of Guam. Fishery-independent size composition and relative abundance data from diver surveys data from 2014 to 2017, along with fishery-dependent data from biosampling and creel surveys for 2013 to 2016, and life-history data were incorporated into the length-based model.

-   Nadon, Marc O. 2019. [Stock Assessment of Guam Coral Reef Fish, 2019](https://repository.library.noaa.gov/view/noaa/20062)
