---
title: Striped Marlin
---

Striped marlin (*Kajikia audax*) are widely distributed in the tropical and subtropical waters of the Pacific and Indian Oceans. In the North Pacific, the Western and Central North Pacific Ocean (WCNPO) stock is conventionally defined as occurring north of the Equator (0°) and west of 150°W within the Western and Central Pacific Fisheries Commission (WCPFC) Convention Area.

Striped marlin are predominantly taken as incidental catch in pelagic longline fisheries targeting tunas and swordfish, mainly by fleets from Japan, the United States, Korea, and Chinese Taipei, with additional catch from China and other WCPFC members. Catches were highest from the 1970s through the 1990s and were largely associated with large-scale high-seas driftnet fleets. Since the 1990s most landings have come from longline fleets, with overall catches declining.

Because striped marlin are highly migratory and cross international boundaries, stock assessments are conducted through international scientific bodies. The International Scientific Committee for Tuna and Tuna-like Species in the North Pacific Ocean (ISC) [Billfish Working Group]({{< var partner.BILLWG.href >}}) (BILLWG) assesses the Western and Central North Pacific Ocean striped marlin stock. The ISC BILLWG comprises scientists from ISC member nations and observers who regularly evaluate billfish fisheries and provide science-based advice for conservation and management.

## Assessmment

*Stock status and conservation information for WCNPO striped marlin are based on the most recent benchmark assessment in 2023.*

-   In **2023**, the ISC BILLWG conducted the most recent benchmark assessment of Western and Central North Pacific Ocean striped marlin using Stock Synthesis. The assessment model was an integrated age- and length-structured framework fit to time series (1977–2020) of catch, standardized catch-per-unit-effort indices contributed by Chinese Taipei, Japan, and the United States as well as length-composition data compiled from ISC members and other WCPFC members. Life-history parameters for growth and maturity were updated for this benchmark. Estimates of spawning biomass, fishing mortality, and their associated uncertainties were used to determine ISC stock status and conservation information and to develop projections to rebuild the stock (see [ISC Plenary, 2025](https://isc.fra.go.jp/pdf/ISC25/ISC25_Plenary_Report_FINAL.pdf), pp. 77-80).

## Publications

-   [ISC BILLWG 2023 Assessment Report (PDF)](https://isc.fra.go.jp/pdf/ISC23/ISC23_ANNEX14-Stock_Assessment_Report_for_WCNPO_Striped_Marlin-FINAL.pdf)
