---
title: Swordfish
---

The North Pacific swordfish (*Xiphias gladius*) stock is divided into two sub-stocks, the Western and Central North Pacific Ocean sub-stock and the North Eastern Pacific Ocean sub-stock, by a diagonal boundary line from Baja, California to the equator, but are assessed as a single stock with the spatial component modeled implicitly using fleets-as-areas. Swordfish have high economic value in both commercial and recreational fisheries and are primarily caught with longline fishing gear. Catch was historically greater in the WCNPO than the NEPO, since 2011, annual catches are approximately 10,000 mt for both areas.

Swordfish are highly migratory species and cross international boundaries, which necessitates the need to assess their populations on an international scale. The North Pacific swordfish stocks are assessed by the International Scientific Committee for Tuna and Tuna-like Species in the North Pacific (ISC) [Billfish working group]({{< var partner.BILLWG.href >}}) (BILLWG), which is a collaborative effort between multinational and multi-regional fisheries management organizations that conducts assessments and provides scientific advice for swordfish and marlin species.

The most recent benchmark stock assessment for the WCNPO swordfish stock was conducted in 2023. The assessment model was an integrated, age- and sex-structured model in Stock Synthesis. It included best-available catch, catch-per-unit-effort (CPUE), and length composition data from 1975 to 2021. This assessment indicated that the stock was not overfished and that overfishing was not occuring according to MSY-based reference points.

## Publications

-   [ISC BILLWG 2023 Assessment Report (PDF)](https://isc.fra.go.jp/pdf/ISC23/ISC23_ANNEX11-Stock_Assessment_Report_for_North_Pacific_Ocean_Swordfish_FINAL.pdf)
