---
title: Uku Snapper
---

The ukupalu snapper, more commonly known as *uku*, is found throughout the Hawaiian Archipelago (the northwestern and main Hawaiian Islands) at depths of 60 to 650 feet. Uku have been fished for hundreds of years in the Hawaiian Archipelago region. It is a particularly important resource for recreational and subsistence fishers; these fisheries account for over half of the total annual uku catches, at 50 and 100 mt per year.

The commercial fishery has experienced increases and declines in catches since the 1950s but since the 1990s have been steadily increasing to approximately 50 mt per year around 2015. Recently, the commerical catch has declined to around 25 mt per year. The most common fishing method is deep-sea handline with baited hooks. Currently, the MHI stock is jointly managed by the State of Hawaii Department of Land and Natural Resources and NOAA.

Before 2017, the MHI uku stock was assessed as a part of a snapper complex. Starting in 2020, uku is now assessed as a single-species using the statistical catch-at-age model [Stock Synthesis (version 3.30)](https://github.com/nmfs-stock-synthesis/stock-synthesis/). The model incorporated both fishery-dependent and fishery-independent data.

Fishery-dependent data included individual weights, catch, and catch-per-unit-effort data from the commercial fishery for the years 1948 to 2018 and recreational catch data from the Hawai'i Marine Recreational Fishing Survey for the years 2003 to 2018.

The fishery-independent index of relative abundance data was from the Pacific Reef Assessment and Monitoring Program for the years 2005 to 2016.

The assessment was the first successful implementation of an integrated Stock Synthesis model in Hawai'i and marks a milestone for the stock assessment program and the future of conservation of marine resources in Hawai'i. A 2024 update to the 2020 benchmark mark assessment confirmed that the current status of the stock is not overfished, with no overfishing occuring.

## Repositories

-   [2020 Assessment](https://github.com/noaa-pifsc/2020_Hawaii_Uku)
-   [2024 Assessment Update](https://github.com/noaa-pifsc/2024_Hawaii_Uku)

## Publications

-   Nadon, Marc O.; Sculley, Michelle; Carvalho, Felipe. 2020. [Stock assessment of uku (Aprion virescens) in Hawaii, 2020](https://doi.org/10.25923/57nb-8138)
-   Nadon, Marc O. (2024) Stock assessment of uku (Aprion virescens) in Hawaii, 2024 update.<https://www.fisheries.noaa.gov/resource/document/stock-assessment-uku-aprion-virescens-hawaii-2024-update>
