---
title: "Interactive Science"
---

Interactive web-based tools and websites are being developed to improve communication of the extensive scientific work conducted by PIFSC stock assessment scientists. These resources aim to translate highly technical methods and results for a diverse audience. Scientists have created websites to enhance the documentation of modeling processes and results, and to share detailed presentations and other resources with the public. In addition to these public websites, web-based applications represent a newer approach to making technical analysis results interactive and accessible to our constituents. Interactive web applications can perform analyses in real-time and quickly display key results, eliminating the need for users to possess the technical skills required for the original analysis development. This capability allows reviewers to evaluate the robustness and validity of our analyses, enables council members to assimilate crucial model information in manageable segments, and permits constituents to observe the impact of their assumptions and knowledge on fishery management measures, such as total allowable catch. The implementation of these new tools has significantly improved our ability to communicate how analyses are conducted and the subsequent impacts of those results on fisheries and fishers.
